---
- name: install rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
  args:
    creates: ~/.cargo/bin/rustup
  tags: ["skip_ansible_lint"]

- name: create rust completions file
  copy:
    content: ""
    dest: "{{ rustup_completions }}"
    force: false

- name: create rust bash completions
  shell: "~/.cargo/bin/rustup completions bash > {{ rustup_completions }}"
  args:
    creates: "{{ rustup_completions }}"

- name: add rust to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: true
    marker: "### {mark} ANSIBLE MANAGED RUST CONFIG ###"
    block: |
      source $HOME/.cargo/env

- name: install rust crates
  # Use --force until we get --update
  # https://github.com/rust-lang/cargo/issues/2082
  command: '/usr/bin/env bash -l -c "rustup run stable cargo install --force {{ item }}"'
  with_items: "{{ crates }}"
  tags: ["skip_ansible_lint"]
