---
- name: Install vscode, extensions, & settings
  include_role:
    name: gantsign.visual-studio-code
  vars:
    users: "{{ vscode_users }}"

- name: Add editor to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: true
    mode: "0644"
    marker: "### {mark} ANSIBLE MANAGED EDITOR CONFIG ###"
    block: |
      # Set editor and git editor
      export EDITOR="code"
      export GIT_EDITOR="code --wait"
