- name: install vscode, extensions, & settings
  include_role:
    name: gantsign.visual-studio-code
  vars:
    users: "{{ vscode_users }}"

- name: add editor to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: yes
    marker: "### {mark} ANSIBLE MANAGED EDITOR CONFIG ###"
    block: |
      # Set editor and git editor
      export EDITOR="code"
      export GIT_EDITOR="code --wait"
