---
- name: install bash-it
  git:
    repo: "https://github.com/Bash-it/bash-it.git"
    dest: "{{ bash_it_install_path }}"
    version: "v3.0.2"
  register: bash_it_checkout

- name: add bash-it to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: yes
    marker: "### {mark} ANSIBLE MANAGED BASH-IT CONFIG ###"
    block: |
      # Path to the bash it configuration
      export BASH_IT="{{ bash_it_install_path }}"

      # Lock and Load a custom theme file
      export BASH_IT_THEME="{{ bash_it_theme }}"

      # Load Bash It
      source $BASH_IT/bash_it.sh

- name: migrate bash-it to latest versions
  become: yes
  command: '/bin/bash -l -c "bash-it migrate"'
  when: bash_it_checkout.before != None and bash_it_checkout.before != bash_it_checkout.after

- name: install bash-it aliases, completions, and plugins
  command: '/bin/bash -l -c "bash-it enable {{ item.to_enable }} {{ item.list | join('' '') }}"'
  register: result
  changed_when: "result.stdout_lines | reject('match', '.* is already enabled.') | list | length"
  with_items:
    - { to_enable: alias, list: "{{ bash_it_aliases }}" }
    - { to_enable: completion, list: "{{ bash_it_completions }}" }
    - { to_enable: plugin, list: "{{ bash_it_plugins }}" }
