---
- hosts: localhost
  connection: local

  roles:
    - { role: dotfiles, tags: ["dotfiles"] }
    - role: osx
      tags: ["osx"]
      when: ansible_distribution == 'MacOSX'
    - role: homebrew
      tags: ["homebrew"]
      when: ansible_distribution == 'MacOSX'
    - role: homebrew_cask
      tags: ["cask"]
      when: ansible_distribution == 'MacOSX'
    # - role: geerlingguy.mas # TODO(James) this fails in tests
    #   tags: ["mas"]
    #   when: ansible_distribution == 'MacOSX'
    - role: bash
      tags: ["bash"]
      when: ansible_distribution == 'MacOSX'
    - { role: bash_it, tags: ["bash-it"] }
    - { role: editor, tags: ["editor"] }
    - { role: node, tags: ["never", "node"] }
    - { role: php, tags: ["never", "php"] }
    - { role: rust, tags: ["never", "rust"] }
