---

- hosts: localhost
  connection: local

  roles:
    #- osx
    - homebrew
    - homebrew-cask
    - bash-it
    - atom
    - bash
    - mysql
    - node
    - php

  vars:
    osx_defaults:
      -
    atom_packages_packages:
      - atom-handlebars
      - atomic-chrome
      - auto-update-packages
      - autocomplete-modules
      - busy-signal
      - config-import-export
      - docblockr
      - eclectic-syntax
      - editorconfig
      - elmjutsu
      - emmet
      - file-icons
      - firewatch-syntax
      - go-debug
      - go-plus
      - go-rename
      - go-signature-statusbar
      - highlight-selected
      - hyperclick
      - imdone-atom
      - intentions
      - language-ansible
      - language-api-blueprint
      - language-elm
      - language-gitignore
      - language-haskell
      - linter
      - linter-alex
      - linter-api-blueprint
      - linter-just-say-no
      - linter-ui-default
      - linter-write-good
      - markdown-writer
      - marked
      - merge-conflicts
      - minimap
      - oblique-strategies
      - pigments
      - react
    homebrew_taps:
      - homebrew/services
      - caskroom/fonts
      - caskroom/versions
    homebrew_formula:
      - ansible
      - bash-completion
      - bat
      - composer
      - curl
      - fasd
      - git
      - git-flow
      - gnu-tar
      - go
      - hr
      - TomAnthony/brews/itermocil
      - karn
      - legit
      - mackup
      - php-code-sniffer
      - php-cs-fixer
      - phpunit
      - rsync
      - trash
      - travis
      - wget
      - whois
      - wp-cli
      - yarn
    homebrew_casks:
      - a-better-finder-attributes
      - a-better-finder-rename
      - alfred
      - android-file-transfer
      - bartender
      - big-mean-folder-machine
      - calibre
      - cheatsheet
      - clamxav
      - cleanmymac
      - dash2
      - deeper
      - devonthink-pro-office
      - diffmerge
      - dropbox
      - dropzone
      - firefox
      - firefoxdeveloperedition
      - flux
      - font-source-code-pro
      - google-chrome
      - hazel
      - insync
      - iterm2
      - malwarebytes-anti-malware
      - omnidisksweeper
      - onyx
      - owncloud
      - postbox
      - sequel-pro
      - setapp
      - skitch
      - slack
      - spectacle
      - spillo
      - superduper
      - tower
      - transmit
      - vagrant
      - virtualbox
    bash_it_plugins:
      - alias-completion
      - base
      - battery
      - browser
      - dirs
      - explain
      - extract
      - fasd
      - gif
      - git
      - go
      - history
      - osx
      - projects
      - ssh
    bash_it_aliases:
      - ansible
      - atom
      - curl
      - general
      - git
      - homebrew-cask
      - homebrew
      - npm
      - osx
      - vagrant
      - yarn
    bash_it_completions:
      - apm
      - bash-it
      - brew
      - composer
      - defaults
      - dirs
      - export
      - git
      - go
      - gulp
      - makefile
      - npm
      - projects
      - ssh
      - system
      - travis
      - vagrant
      - virtualbox
