---
- hosts: localhost
  connection: local

  roles:
    #- { role: osx, tags: ["osx"] }
    - { role: homebrew, tags: ["homebrew"] }
    - { role: homebrew-cask, tags: ["cask"] }
    - { role: bash-it, tags: ["bash-it"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: atom, tags: ["atom"] }
    - { role: bash, tags: ["bash"] }
    - { role: karn, tags: ["karn"] }
    - { role: mackup, tags: ["mackup"] }
    - { role: mysql, tags: ["mysql"] }
    - { role: node, tags: ["node"] }
    - { role: php, tags: ["php"] }
    - { role: rust, tags: ["rust"] }
    - { role: geerlingguy.mas, tags: ["mas"] }
