---

- hosts: localhost
  connection: local

  roles:
    #- osx
    - homebrew
    - homebrew-cask
    - bash-it
    - dotfiles
    - atom
    - bash
    - karn
    - mackup
    - mysql
    - node
    - php
    - rust
    - geerlingguy.mas

  vars:
    computer_name: "Roma"
    timezone: "America/New_York"
    osx_defaults:
      #################
      # General UI/UX #
      #################

      # Show scrollbars when scrolling
      - domain: "NSGlobalDomain"
        key: "AppleShowScrollBars"
        type: string
        value: "WhenScrolling"
      # Increase window resize speed for Cocoa applications
      - domain: "NSGlobalDomain"
        key: "NSWindowResizeTime"
        type: float
        value: 0.001
      # Expand save panel by default
      - domain: "NSGlobalDomain"
        key: "NSNavPanelExpandedStateForSaveMode"
        type: bool
        value: true
      - domain: "NSGlobalDomain"
        key: "NSNavPanelExpandedStateForSaveMode2"
        type: bool
        value: true
      # Expand print panel by default
      - domain: "NSGlobalDomain"
        key: "PMPrintingExpandedStateForPrint"
        type: bool
        value: true
      # Expand print panel by default
      - domain: "NSGlobalDomain"
        key: "PMPrintingExpandedStateForPrint2"
        type: bool
        value: true
      # Automatically quit printer app once the print jobs complete
      - domain: "com.apple.print.PrintingPrefs"
        key: "Quit When Finished"
        type: bool
        value: true
      # Disable the "Are you sure you want to open this application?"
      # dialog
      - domain: "com.apple.LaunchServices"
        key: "LSQuarantine"
        type: bool
        value: false
      # Disable smart quotes
      - domain: "NSGlobalDomain"
        key: "NSAutomaticQuoteSubstitutionEnabled"
        type: bool
        value: false
      # Disable smart dashes
      - domain: "NSGlobalDomain"
        key: "NSAutomaticDashSubstitutionEnabled"
        type: bool
        value: false
      # Disable automatic capitalization
      - domain: "NSGlobalDomain"
        key: "NSAutomaticCapitalizationEnabled"
        type: bool
        value: false
      # Disable automatic period substitution
      - domain: "NSGlobalDomain"
        key: "NSAutomaticPeriodSubstitutionEnabled"
        type: bool
        value: false
      # Reveal IP address, hostname, OS version, etc.
      # when clicking the clock in the login window
      - domain: "com.apple.loginwindow"
        key: "AdminHostInfo"
        type: string
        value: "HostName"
      # Disable transparency in the menu bar and elsewhere on Yosemite
      - domain: "com.apple.universalaccess"
        key: "reduceTransparency"
        type: bool
        value: false
      # Set sidebar icon size to medium
      - domain: "NSGlobalDomain"
        key: "NSTableViewDefaultSizeMode"
        type: int
        value: 2
      # Disable the over-the-top focus ring animation
      - domain: "NSGlobalDomain"
        key: "NSUseAnimatedFocusRing"
        type: bool
        value: false
      # Increase window resize speed for Cocoa applications
      - domain: "NSGlobalDomain"
        key: "NSWindowResizeTime"
        type: float
        value: 0.001
      # Save to disk (not to iCloud) by default
      - domain: "NSGlobalDomain"
        key: "NSDocumentSaveNewDocumentsToCloud"
        type: bool
        value: false
      # Display ASCII control characters using caret notation
      # in standard text views
      - domain: "NSGlobalDomain"
        key: "NSTextShowsControlCharacters"
        type: bool
        value: true
      # Disable automatic termination of inactive apps
      - domain: "NSGlobalDomain"
        key: "NSDisableAutomaticTermination"
        type: bool
        value: true
      # Set Help Viewer windows to non-floating mode
      - domain: "com.apple.helpviewer"
        key: "DevMode"
        type: bool
        value: true

      ###############################################################
      # Trackpad, mouse, keyboard, Bluetooth accessories, and input #
      ###############################################################

      # Enable full keyboard access for all controls
      # (e.g. enable Tab in modal dialogs)
      - domain: "NSGlobalDomain"
        key: "AppleKeyboardUIMode"
        type: int
        value: 3
      # Disable press-and-hold for keys in favor of key repeat
      - domain: "NSGlobalDomain"
        key: "ApplePressAndHoldEnabled"
        type: bool
        value: false
      # Set a blazingly fast keyboard repeat rate
      - domain: "NSGlobalDomain"
        key: "KeyRepeat"
        type: int
        value: 1
      - domain: "NSGlobalDomain"
        key: "InitialKeyRepeat"
        type: int
        value: 10
      # Set language and text formats
      - domain: "NSGlobalDomain"
        key: "AppleLanguages"
        type: array
        value:
          - "en"
      - domain: "NSGlobalDomain"
        key: "AppleLocale"
        type: string
        value: "en_US@currency=USD"
      - domain: "NSGlobalDomain"
        key: "AppleMeasurementUnits"
        type: string
        value: "Inches"
      - domain: "NSGlobalDomain"
        key: "AppleMetricUnits"
        type: bool
        value: false
      # Disable auto-correct
      - domain: "NSGlobalDomain"
        key: "NSAutomaticSpellingCorrectionEnabled"
        type: bool
        value: false
      # Disable "natural" scrolling
      - domain: "NSGlobalDomain"
        key: "com.apple.swipescrolldirection"
        type: bool
        value: false
      # Increase sound quality for Bluetooth headphones/headsets
      - domain: "com.apple.BluetoothAudioAgent"
        key: "Apple Bitpool Min (editable)"
        type: int
        value: 40
      # Enable full keyboard access for all controls
      # (e.g. enable Tab in modal dialogs)
      - domain: "NSGlobalDomain"
        key: "AppleKeyboardUIMode"
        type: int
        value: 3
      # Use scroll gesture with the Ctrl (^) modifier key to zoom
      - domain: "com.apple.universalaccess"
        key: "closeViewScrollWheelToggle"
        type: bool
        value: true
      - domain: "com.apple.universalaccess"
        key: "HIDScrollZoomModifierMask"
        type: int
        value: 262144
      # Follow the keyboard focus while zoomed in
      - domain: "com.apple.universalaccess"
        key: "closeViewZoomFollowsFocus"
        type: bool
        value: true

      ##########
      # Screen #
      ##########

      # Require password immediately after sleep or screen saver begins
      - domain: "com.apple.screensaver"
        key: "askForPassword"
        type: int
        value: 1
      - domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0
      # Save screenshots to the desktop
      # - domain: "com.apple.screencapture"
      #   key: "location"
      #   type: string
      #   value: "${HOME}/Desktop"
      # Save screenshots in JPG format
      - domain: "com.apple.screencapture"
        key: "type"
        type: string
        value: "jpg"
      # Disable shadow in screenshots
      - domain: "com.apple.screencapture"
        key: "disable-shadow"
        type: bool
        value: true
      # Enable subpixel font rendering on non-Apple LCDs
      - domain: "NSGlobalDomain"
        key: "AppleFontSmoothing"
        type: int
        value: 2

      ##########
      # Finder #
      ##########

      # Show icons for hard drives, servers,
      # and removable media on the desktop
      - domain: "com.apple.finder"
        key: "ShowExternalHardDrivesOnDesktop"
        type: bool
        value: true
      - domain: "com.apple.finder"
        key: "ShowHardDrivesOnDesktop"
        type: bool
        value: true
      - domain: "com.apple.finder"
        key: "ShowMountedServersOnDesktop"
        type: bool
        value: true
      - domain: "com.apple.finder"
        key: "ShowRemovableMediaOnDesktop"
        type: bool
        value: true
      # Finder: show all filename extensions
      - domain: "NSGlobalDomain"
        key: "AppleShowAllExtensions"
        type: bool
        value: true
      # Finder: show status bar
      - domain: "com.apple.finder"
        key: "ShowStatusBar"
        type: bool
        value: true
      # Finder: show path bar
      - domain: "com.apple.finder"
        key: "ShowPathbar"
        type: bool
        value: true
      # Finder: allow text selection in Quick Look
      - domain: "com.apple.finder"
        key: "QLEnableTextSelection"
        type: bool
        value: true
      # Display full POSIX path as Finder window title
      - domain: "com.apple.finder"
        key: "_FXShowPosixPathInTitle"
        type: bool
        value: true
      # When performing a search, search the current folder by default
      - domain: "com.apple.finder"
        key: "FXDefaultSearchScope"
        type: string
        value: "SCcf"
      # Disable the warning when changing a file extension
      - domain: "com.apple.finder"
        key: "FXEnableExtensionChangeWarning"
        type: bool
        value: false
      # Enable spring loading for directories
      - domain: "NSGlobalDomain"
        key: "com.apple.springing.enabled"
        type: bool
        value: true
      # Remove the spring loading delay for directories
      - domain: "NSGlobalDomain"
        key: "com.apple.springing.delay"
        type: float
        value: 0
      # Avoid creating .DS_Store files on network volumes
      - domain: "com.apple.desktopservices"
        key: "DSDontWriteNetworkStores"
        type: bool
        value: true
      # Use column view in all Finder windows by default
      - domain: "com.apple.finder"
        key: "FXPreferredViewStyle"
        type: string
        value: "clmv"
      # Disable the warning before emptying the Trash
      - domain: "com.apple.finder"
        key: "WarnOnEmptyTrash"
        type: bool
        value: false
      # Don't open a Finder window when mounting an external disk
      - domain: "com.apple.finder"
        key: "OpenWindowForNewRemovableDisk"
        type: bool
        value: false

      ####################################
      # Dock, Dashboard, and hot corners #
      ####################################

      # Minimize windows into their application's icon
      - domain: "com.apple.dock"
        key: "minimize-to-application"
        type: bool
        value: true
      # Show indicator lights for open applications in the Dock
      - domain: "com.apple.dock"
        key: "show-process-indicators"
        type: bool
        value: true
      # Hot corners
      # Possible values:
      #  0: No-op
      #  2: Mission Control
      #  3: Show application windows
      #  4: Desktop
      #  5: Start screen saver
      #  6: Disable screen saver
      #  7: Dashboard
      # 10: Put display to sleep
      # 11: Launchpad
      # 12: Notification Center
      # Top left screen corner – Put display to sleep
      - domain: "com.apple.dock"
        key: "wvous-tl-corner"
        type: int
        value: 10
      - domain: "com.apple.dock"
        key: "wvous-tl-modifier"
        type: int
        value: 0
      # Top right screen corner – No-op
      - domain: "com.apple.dock"
        key: "wvous-tr-corner"
        type: int
        value: 0
      - domain: "com.apple.dock"
        key: "wvous-tr-modifier"
        type: int
        value: 0
      # Bottom right screen corner – Desktop
      - domain: "com.apple.dock"
        key: "wvous-br-corner"
        type: int
        value: 4
      - domain: "com.apple.dock"
        key: "wvous-br-modifier"
        type: int
        value: 0
      # Bottom left screen corner – Mission control
      - domain: "com.apple.dock"
        key: "wvous-bl-corner"
        type: int
        value: 2
      - domain: "com.apple.dock"
        key: "wvous-bl-modifier"
        type: int
        value: 0
      # Make Dock icons of hidden applications translucent
      - domain: "com.apple.dock"
        key: "showhidden"
        type: bool
        value: true

      ########
      # Apps #
      ########

      # Use plain text mode for new TextEdit documents
      - domain: "com.apple.TextEdit"
        key: "RichText"
        type: int
        value: 0
      # Open and save files as UTF-8 in TextEdit
      - domain: "com.apple.TextEdit"
        key: "PlainTextEncoding"
        type: int
        value: 4
      - domain: "com.apple.TextEdit"
        key: "PlainTextEncodingForWrite"
        type: int
        value: 4
      # Enable the debug menu in Disk Utility
      - domain: "com.apple.DiskUtility"
        key: "DUDebugMenuEnabled"
        type: bool
        value: true
      - domain: "com.apple.DiskUtility"
        key: "advanced-image-options"
        type: bool
        value: true
      # Enable Debug Menu in the Mac App Store
      - domain: "com.apple.appstore"
        key: "ShowDebugMenu"
        type: bool
        value: true
      # Allow installing user scripts via GitHub or Userscripts.org
      - domain: "com.google.Chrome"
        key: "ExtensionInstallSources"
        type: array
        value:
          - "https://*.github.com/*"
          - "http://userscripts.org/*"
      # Allow installing user scripts via GitHub or Userscripts.org
      - domain: "com.google.Chrome.canary"
        key: "ExtensionInstallSources"
        type: array
        value:
          - "https://*.github.com/*"
          - "http://userscripts.org/*"
    mas_email: "jamesorodig@gmail.com"
    mas_signin_dialog: yes
    mas_upgrade_all_apps: yes
    mas_installed_apps:
      - id: 523620159
        name: "CleanMyDrive 2 (2.1.11)"
      - id: 678464954
        name: "NetSpot Wi-Fi Reporter (2.1.475)"
      - id: 670592452
        name: "Tyme (2.5.5)"
      - id: 412448059
        name: "ForkLift (2.6.6)"
      - id: 423081863
        name: "AppShelf (2.3.4)"
      - id: 514951692
        name: "NetSpot (1.3.418)"
      - id: 866773894
        name: "Quiver (3.1.3)"
      - id: 1160131071
        name: "Sluggard (2.1.1)"
      - id: 890031187
        name: "Marked 2 (2.5.14)"
      - id: 568494494
        name: "Pocket (1.7.8)"
      - id: 410628904
        name: "Wunderlist (3.4.8)"
      - id: 457622435
        name: "Yoink (3.4.2)"
      - id: 522090209
        name: "PDFGenius (4.8)"
    atom_packages_packages:
      - atom-handlebars
      - atom-ide-ui
      - atomic-chrome
      - auto-update-packages
      - autocomplete-modules
      - busy-signal
      - config-import-export
      - docblockr
      - eclectic-syntax
      - editorconfig
      - elmjutsu
      - emmet
      - file-icons
      - firewatch-syntax
      - git-blame
      - go-debug
      - go-plus
      - go-rename
      - go-signature-statusbar
      - highlight-selected
      - hyperclick
      - ide-css
      - ide-flowtype
      - ide-php
      - ide-rust
      - imdone-atom
      - intentions
      - language-ansible
      - language-api-blueprint
      - language-cshtml
      - language-elm
      - language-gherkin
      - language-gitignore
      - language-haskell
      - language-rust
      - language-vue
      - linter-api-blueprint
      - linter-eslint
      - linter-ui-default
      - linter-write-good
      - markdown-writer
      - marked
      - merge-conflicts
      - minimap
      - multi-cursor
      - oblique-strategies
      - pigments
      - react
      - todo
    homebrew_taps:
      - homebrew/services
      - homebrew/cask-fonts
      - homebrew/cask-versions
    homebrew_formula:
      - ansible
      - bash-completion
      - bat
      - composer
      - curl
      - fasd
      - git
      - git-flow
      - gnu-tar
      - go
      - hr
      - TomAnthony/brews/itermocil
      - legit
      - mackup
      - php-code-sniffer
      - php-cs-fixer
      - phpunit
      - rsync
      - trash
      - travis
      - wget
      - whois
      - wp-cli
      - yarn
    homebrew_casks:
      - a-better-finder-attributes
      - a-better-finder-rename
      - alfred
      - android-file-transfer
      - bartender
      - big-mean-folder-machine
      - calibre
      - cheatsheet
      - clamxav
      - cleanmymac
      - dash2
      - deeper
      - devonthink-pro-office
      - diffmerge
      - dropbox
      - dropzone
      - firefox
      - firefoxdeveloperedition
      - flux
      - font-source-code-pro
      - google-chrome
      - hazel
      - insync
      - iterm2
      - malwarebytes-anti-malware
      - omnidisksweeper
      - onyx
      - owncloud
      - postbox
      - sequel-pro
      - setapp
      - skitch
      - slack
      - spectacle
      - spillo
      - superduper
      - tower
      - transmit
      - vagrant
      - virtualbox
    bash_it_plugins:
      - alias-completion
      - base
      - battery
      - browser
      - dirs
      - explain
      - extract
      - fasd
      - gif
      - git
      - go
      - history
      - osx
      - projects
      - ssh
    bash_it_aliases:
      - ansible
      - atom
      - curl
      - general
      - git
      - homebrew-cask
      - homebrew
      - npm
      - osx
      - vagrant
      - yarn
    bash_it_completions:
      - apm
      - bash-it
      - brew
      - composer
      - defaults
      - dirs
      - export
      - git
      - go
      - gulp
      - makefile
      - npm
      - projects
      - ssh
      - system
      - travis
      - vagrant
      - virtualbox
    crates:
      - rustfmt
