---
- hosts: localhost
  connection: local

  roles:
    - { role: dotfiles, tags: ["dotfiles", "all"] }
    - role: osx
      tags: ["osx", "all"]
      when: ansible_distribution == 'MacOSX'
    - role: homebrew
      tags: ["homebrew", "all"]
      when: ansible_distribution == 'MacOSX'
    - role: homebrew_cask
      tags: ["cask", "all"]
      when: ansible_distribution == 'MacOSX'
    # - role: geerlingguy.mas # TODO(James) this fails in tests
    #   tags: ["mas", "all"]
    #   when: ansible_distribution == 'MacOSX'
    - role: bash
      tags: ["bash", "all"]
      when: ansible_distribution == 'MacOSX'
    - { role: bash_it, tags: ["bash-it", "all"] }
    - { role: editor, tags: ["editor", "all"] }
    - { role: node, tags: ["node", "all", "never"] }
    - { role: php, tags: ["php", "all", "never"] }
    - { role: rust, tags: ["rust", "never"] }
