---

- hosts: localhost
  connection: local

  roles:
    #- osx
    - homebrew
    - homebrew-cask
    - atom
    - bash
    - mysql
    - node
    - php

  vars:
    osx_defaults:
      -
    atom_packages_packages:
      - elmjutsu
    homebrew_taps:
      - homebrew/services
      - caskroom/fonts
      - caskroom/versions
    homebrew_formula:
      - ansible
      - bash-completion
      - bat
      - composer
      - curl
      - fasd
      - git
      - git-flow
      - gnu-tar
      - go
      - hr
      - TomAnthony/brews/itermocil
      - karn
      - mackup
      - php-code-sniffer
      - php-cs-fixer
      - phpunit
      - rsync
      - trash
      - wget
      - whois
      - wp-cli
      - yarn
    homebrew_casks:
      - a-better-finder-attributes
      - a-better-finder-rename
      - alfred
      - android-file-transfer
      - bartender
      - big-mean-folder-machine
      - calibre
      - cheatsheet
      - clamxav
      - cleanmymac
      - dash2
      - deeper
      - devonthink-pro-office
      - diffmerge
      - dropbox
      - dropzone
      - firefox
      - firefoxdeveloperedition
      - flux
      - font-source-code-pro
      - google-chrome
      - hazel
      - insync
      - iterm2
      - malwarebytes-anti-malware
      - omnidisksweeper
      - onyx
      - owncloud
      - postbox
      - sequel-pro
      - setapp
      - skitch
      - slack
      - spectacle
      - spillo
      - superduper
      - tower
      - transmit
      - vagrant
      - virtualbox
