---
- name: Personal computer playbook
  hosts: localhost
  connection: local

  roles:
    - { role: elliotweiser.osx-command-line-tools, tags: [clt] }
    - { role: geerlingguy.mac.homebrew, tags: [homebrew] }
    - { role: geerlingguy.mac.dock, tags: [dock] }
    - { role: shell, tags: [shell] }
    - { role: os, tags: [os] }
    - { role: editor, tags: [editor] }
    - { role: node, tags: [node, never] }
    - { role: php, tags: [php, never] }
    - { role: rust, tags: [rust, never] }
    - { role: python, tags: [python, never] }
