---
- hosts: localhost
  connection: local
  name: Personal computer playbook

  roles:
    - { role: elliotweiser.osx-command-line-tools, tags: [clt, all] }
    - { role: geerlingguy.mac.homebrew, tags: [homebrew, all] }
    - { role: geerlingguy.mac.dock, tags: [dock, all] }
    - { role: shell, tags: [bash-it, all] }
    - { role: config, tags: [config, all] }
    - { role: editor, tags: [editor, all] }
    - { role: node, tags: [node, never] }
    - { role: php, tags: [php, never] }
    - { role: rust, tags: [rust, never] }
