---
- hosts: localhost
  connection: local

  roles:
    - { role: elliotweiser.osx-command-line-tools, tags: ["clt", "all"] }
    - { role: config, tags: ["config", "all"] }
    - { role: packages, tags: ["packages", "all"] }
    - { role: apps, tags: ["apps", "all"] }
    - { role: bash_it, tags: ["bash-it", "all"] }
    - { role: editor, tags: ["editor", "all"] }
    - { role: docker, tags: ["docker", "all", "never"] }
    - { role: node, tags: ["node", "all", "never"] }
    - { role: php, tags: ["php", "all", "never"] }
    - { role: rust, tags: ["rust", "all", "never"] }
    # TODO add roles
    # - { role: python, tags: ["python", "all", "never"] }
    # - { role: go, tags: ["go", "all", "never"] }
