---

- hosts: localhost
  connection: local

  roles:
    #- osx
    - homebrew
    - homebrew-cask
    - atom
    - bash
    - mysql
    - php

  vars:
    osx_defaults:
      -
    homebrew_taps:
      - homebrew/services
      - caskroom/fonts
    homebrew_formula:
      - ansible
      - bash-completion
      - composer
      - git
      - git-flow
      - hr
      - mackup
      - php-code-sniffer
      - phpunit
      - rsync
      - trash
      - wget
    homebrew_casks:
      - a-better-finder-attributes
      - a-better-finder-rename
      - alfred
      - bartender
      - big-mean-folder-machine
      - calibre
      - cheatsheet
      - clamxav
      - cleanmymac
      - dash
      - diffmerge
      - dropzone
      - firefox
      - flux
      - font-source-code-pro
      - deeper
      - dropbox
      - google-chrome
      - insync
      - iterm2
      - omnidisksweeper
      - onyx
      - owncloud
      - postbox
      - sequel-pro
      - setapp
      - skitch
      - superduper
      - tower
      - transmit
      - vagrant
      - virtualbox
