---
roles:
  - name: elliotweiser.osx-command-line-tools

  - name: geerlingguy.docker
    src: geerlingguy.docker
    version: 4.2.2

  - name: gantsign.visual-studio-code
    src: gantsign.visual-studio-code
    version: 6.8.0

collections:
  - name: geerlingguy.mac
  - name: community.general
