---
- name: geerlingguy.mas
  src: geerlingguy.mas
  version: 1.2.0

- name: geerlingguy.docker
  src: geerlingguy.docker
  version: 4.2.2

- name: gantsign.visual-studio-code
  src: gantsign.visual-studio-code
  version: 6.8.0
