---
- name: Install packages
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ item }}"
  with_items: "{{ snap_apps }}"
