---
- name: Install osx packages
  include_tasks: install-osx-packages.yml
  when: ansible_distribution == 'MacOSX'

- name: Install ubuntu packages
  include_tasks: install-ubuntu-packages.yml
  when: ansible_distribution == 'Ubuntu'
