---
atom_packages_packages:
  - atom-handlebars
  - atom-ide-ui
  - atomic-chrome
  - auto-update-packages
  - autocomplete-modules
  - busy-signal
  - config-import-export
  - docblockr
  - eclectic-syntax
  - editorconfig
  - elmjutsu
  - emmet
  - file-icons
  - firewatch-syntax
  - git-blame
  - go-debug
  - go-plus
  - go-rename
  - go-signature-statusbar
  - highlight-selected
  - hyperclick
  - ide-css
  - ide-flowtype
  - ide-php
  - ide-rust
  - imdone-atom
  - intentions
  - language-ansible
  - language-api-blueprint
  - language-cshtml
  - language-elm
  - language-gherkin
  - language-gitignore
  - language-haskell
  - language-rust
  - language-vue
  - linter-eslint
  - linter-ui-default
  - linter-write-good
  - markdown-writer
  - marked
  - merge-conflicts
  - minimap
  - multi-cursor
  - oblique-strategies
  - pigments
  - prettier-atom
  - react
  - todo
