---
homebrew_casks:
  - a-better-finder-attributes
  - a-better-finder-rename
  - alfred
  - android-file-transfer
  - bartender
  - big-mean-folder-machine
  - calibre
  - cheatsheet
  - clamxav
  - cleanmymac
  - dash2
  - deeper
  - devonthink
  - diffmerge
  - dropbox
  - dropzone
  - firefox
  - firefox-developer-edition
  - flux
  - font-source-code-pro
  - google-chrome
  - hazel
  - insync
  - iterm2
  - malwarebytes
  - omnidisksweeper
  - onyx
  - owncloud
  - postbox
  - sequel-pro
  - setapp
  - skitch
  - slack
  - spectacle
  - spillo
  - superduper
  - tower2
  - transmit
  - vagrant
  - virtualbox
