---
# Docker Compose options.
docker_install_compose: true
docker_compose_version: "v2.4.1"
docker_compose_path: /usr/libexec/docker/cli-plugins/docker-compose

# A list of users who will be added to the docker group.
docker_users:
  - jamesdigioia
