---
homebrew_taps:
  - homebrew/services
  - homebrew/cask-fonts
  - homebrew/cask-versions
homebrew_formula:
  - bash-completion
  - curl
  - git
  - gnu-tar
  - jq
  - jump
  - ripgrep
  - rsync
  - trash
  - wget
  - whois
