---
homebrew_taps:
  - homebrew/services
  - homebrew/cask-fonts
  - homebrew/cask-versions
homebrew_formula:
  - ansible
  - bash-completion
  - bat
  - curl
  - git
  - gnu-tar
  - go
  - jq
  - jump
  - TomAnthony/brews/itermocil
  - pyenv
  - pyenv-virtualenv
  - ripgrep
  - rsync
  - svn
  - trash
  - wget
  - whois
