---
computer_name: Roma
timezone: America/New_York
osx_defaults:
  #################
  # General UI/UX #
  #################

  # Show scrollbars when scrolling
  - domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: WhenScrolling
  # Increase window resize speed for Cocoa applications
  - domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: !!float "0.001"
  # Expand save panel by default
  - domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  - domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true
  # Expand print panel by default
  - domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  # Expand print panel by default
  - domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true
  # Automatically quit printer app once the print jobs complete
  - domain: com.apple.print.PrintingPrefs
    key: Quit When Finished
    type: bool
    value: true
  # Disable the "Are you sure you want to open this application?"
  # dialog
  - domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
  # Disable smart quotes
  - domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  # Disable smart dashes
  - domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  # Disable automatic capitalization
  - domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
  # Disable automatic period substitution
  - domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
  # Reveal IP address, hostname, OS version, etc.
  # when clicking the clock in the login window
  - domain: com.apple.loginwindow
    key: AdminHostInfo
    type: string
    value: HostName
  # Set sidebar icon size to medium
  - domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2
  # Disable the over-the-top focus ring animation
  - domain: NSGlobalDomain
    key: NSUseAnimatedFocusRing
    type: bool
    value: false
  # Increase window resize speed for Cocoa applications
  - domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: !!float "0.001"
  # Save to disk (not to iCloud) by default
  - domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  # Display ASCII control characters using caret notation
  # in standard text views
  - domain: NSGlobalDomain
    key: NSTextShowsControlCharacters
    type: bool
    value: true
  # Disable automatic termination of inactive apps
  - domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true
  # Set Help Viewer windows to non-floating mode
  - domain: com.apple.helpviewer
    key: DevMode
    type: bool
    value: true

  ###############################################################
  # Trackpad, mouse, keyboard, Bluetooth accessories, and input #
  ###############################################################

  # Enable full keyboard access for all controls
  # (e.g. enable Tab in modal dialogs)
  - domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
  # Disable press-and-hold for keys in favor of key repeat
  - domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  # Set a blazingly fast keyboard repeat rate
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 3
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15
  # Set language and text formats
  - domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en
  - domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: en_US@currency=USD
  - domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Inches
  - domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: false
  # Disable auto-correct
  - domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  # Disable "natural" scrolling
  - domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
  # Increase sound quality for Bluetooth headphones/headsets
  - domain: com.apple.BluetoothAudioAgent
    key: Apple Bitpool Min (editable)
    type: int
    value: 40
  # Enable full keyboard access for all controls
  # (e.g. enable Tab in modal dialogs)
  - domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3

  ##########
  # Screen #
  ##########

  # Require password immediately after sleep or screen saver begins
  - domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
  - domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
  # Save screenshots to the desktop
  - domain: com.apple.screencapture
    key: location
    type: string
    value: ${HOME}/Desktop
  # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
  - domain: com.apple.screencapture
    key: type
    type: string
    value: png
  # Disable shadow in screenshots
  - domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  # Enable subpixel font rendering on non-Apple LCDs
  - domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 2

  ##########
  # Finder #
  ##########

  # Show icons for hard drives, servers,
  # and removable media on the desktop
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
  # Finder: show all filename extensions
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  # Finder: show status bar
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  # Finder: show path bar
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  # Finder: allow text selection in Quick Look
  - domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true
  # Display full POSIX path as Finder window title
  - domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  # Keep folders on top when sorting by name
  - domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  # When performing a search, search the current folder by default
  - domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  # Disable the warning when changing a file extension
  - domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  # Enable spring loading for directories
  - domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true
  # Remove the spring loading delay for directories
  - domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0
  # Avoid creating .DS_Store files on network volumes
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  # Use column view in all Finder windows by default
  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv
  # Disable the warning before emptying the Trash
  - domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false
  # Don't open a Finder window when mounting an external disk
  - domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: false
  # Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
  - domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
  # Disable disk image verification
  - domain: com.apple.frameworks.diskimages
    key: skip-verify
    type: bool
    value: true
  # Automatically open a new Finder window when a volume is mounted
  - domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true
  # Enable AirDrop over Ethernet and on unsupported Macs running Lion
  - domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true

  ####################################
  # Dock, Dashboard, and hot corners #
  ####################################

  # Minimize windows into their application's icon
  - domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  # Enable spring loading for all Dock items
  - domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true
  # Show indicator lights for open applications in the Dock
  - domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
  # Speed up Mission Control animations
  - domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: !!float "0.1"
  # Hot corners
  # Possible values:
  #  0: No-op
  #  2: Mission Control
  #  3: Show application windows
  #  4: Desktop
  #  5: Start screen saver
  #  6: Disable screen saver
  #  7: Dashboard
  # 10: Put display to sleep
  # 11: Launchpad
  # 12: Notification Center
  # Top left screen corner – Put display to sleep
  - domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 0
  - domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0
  # Top right screen corner – No-op
  - domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 0
  - domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0
  # Bottom right screen corner – Desktop
  - domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 0
  - domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: 0
  # Bottom left screen corner – Mission control
  - domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 0
  - domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0
  # Make Dock icons of hidden applications translucent
  - domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  # Enable highlight hover effect for the grid view of a stack (Dock)
  - domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true
  # Set the icon size of Dock items to 36 pixels
  - domain: c
    key: tilesize
    type: float
    value: 70
  # Change minimize/maximize window effect
  - domain: com.apple.dock
    key: mineffect
    type: string
    value: scale
  # Don’t animate opening applications from the Dock
  - domain: com.apple.dock
    key: launchanim
    type: bool
    value: false
  # (i.e. use the old Exposé behavior instead)
  - domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: false
  # Disable Dashboard
  - domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true
  # Don’t show Dashboard as a Space
  - domain: com.apple.dock
    key: dashboard-in-overlay
    type: bool
    value: true
  # Don’t automatically rearrange Spaces based on most recent use
  - domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
  # Automatically hide and show the Dock
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  # Remove the auto-hiding Dock delay
  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  # Remove the animation when hiding/showing the Dock
  - domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0

  ########
  # Apps #
  ########

  # Use plain text mode for new TextEdit documents
  - domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
  # Open and save files as UTF-8 in TextEdit
  - domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
  - domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
  # Enable the debug menu in Disk Utility
  - domain: com.apple.DiskUtility
    key: DUDebugMenuEnabled
    type: bool
    value: true
  - domain: com.apple.DiskUtility
    key: advanced-image-options
    type: bool
    value: true
  # Enable Debug Menu in the Mac App Store
  - domain: com.apple.appstore
    key: ShowDebugMenu
    type: bool
    value: true
  # Enable the WebKit Developer Tools in the Mac App Store
  - domain: com.apple.appstore
    key: WebKitDeveloperExtras
    type: bool
    value: true
  # Enable Debug Menu in the Mac App Store
  - domain: com.apple.appstore
    key: ShowDebugMenu
    type: bool
    value: true
  # Add a context menu item for showing the Web Inspector in web views
  - domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: true
  # Allow installing user scripts via GitHub or Userscripts.org
  - domain: com.google.Chrome
    key: ExtensionInstallSources
    type: array
    value:
      - https://*.github.com/*
      - http://userscripts.org/*
  # Allow installing user scripts via GitHub or Userscripts.org
  - domain: com.google.Chrome.canary
    key: ExtensionInstallSources
    type: array
    value:
      - https://*.github.com/*
      - http://userscripts.org/*
  # Disable the all too sensitive backswipe on trackpads
  - domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false
  # Disable the all too sensitive backswipe on Magic Mouse
  - domain: com.google.Chrome
    key: AppleEnableMouseSwipeNavigateWithScrolls
    type: bool
    value: false
  # Use the system-native print preview dialog
  - domain: com.google.Chrome
    key: DisablePrintPreview
    type: bool
    value: true
  # Expand the print dialog by default
  - domain: com.google.Chrome
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true

  # Disable send and reply animations in Mail.app
  - domain: com.apple.mail
    key: DisableReplyAnimations
    type: bool
    value: true
  # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
  - domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: false
  # Disable inline attachments (just show the icons)
  - domain: com.apple.mail
    key: DisableInlineAttachmentViewing
    type: bool
    value: true
  # Disable automatic spell checking
  - domain: com.apple.mail
    key: SpellCheckingBehavior
    type: string
    value: NoSpellCheckingEnabled
  # See: https://security.stackexchange.com/a/47786/8918
  - domain: com.apple.terminal
    key: SecureKeyboardEntry
    type: bool
    value: true
  # Disable the annoying line marks
  - domain: com.apple.Terminal
    key: ShowLineMarks
    type: int
    value: 0
  # Don’t display the annoying prompt when quitting iTerm
  - domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false
  # Prevent Time Machine from prompting to use new hard drives as backup volume
  - domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
  # Show the main window when launching Activity Monitor
  - domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
  # Visualize CPU usage in the Activity Monitor Dock icon
  - domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5
  # Show all processes in Activity Monitor
  - domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
  # Sort Activity Monitor results by CPU usage
  - domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: CPUUsage
  # Enable the debug menu in iCal (pre-10.8)
  - domain: com.apple.iCal
    key: IncludeDebugMenu
    type: bool
    value: true
  # Use plain text mode for new TextEdit documents
  - domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
  # Open and save files as UTF-8 in TextEdit
  - domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
  # Enable the debug menu in Disk Utility
  - domain: com.apple.DiskUtility
    key: DUDebugMenuEnabled
    type: bool
    value: true
  # Auto-play videos when opened with QuickTime Player
  - domain: com.apple.QuickTimePlayerX
    key: MGPlayMovieOnOpen
    type: bool
    value: true
  # Enable the automatic update check
  - domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: false
  # Check for software updates daily, not just once per week
  - domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
  # Download newly available updates in background
  - domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: int
    value: 1
  # Install System data files & security updates
  - domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: int
    value: 0
  # Automatically download apps purchased on other Macs
  - domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: int
    value: 1
  # Turn off app auto-update
  - domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: false
  # Deny the App Store from reboot machine on macOS updates
  - domain: com.apple.commerce
    key: AutoUpdateRestartRequired
    type: bool
    value: false
