---
vscode_users:
  - username: "{{ lookup('env', 'USER') }}"
    visual_studio_code_settings_overwrite: false
    visual_studio_code_extensions:
      - atlassian.atlascode
      - attilabuti.vscode-mjml
      - bbenoist.vagrant
      - burkeholland.simple-react-snippets
      - dbaeumer.vscode-eslint
      - dhoeric.ansible-vault
      - eamodio.gitlens
      - esbenp.prettier-vscode
      - github.remotehub
      - github.vscode-pull-request-github
      - jakebecker.elixir-ls
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-python.vscode-pylance
      - ms-vscode-remote.remote-containers
      - ms-vscode-remote.remote-ssh
      - ms-vscode-remote.remote-ssh-edit
      - ms-vscode-remote.remote-wsl
      - ms-vscode-remote.vscode-remote-extensionpack
      - ms-vscode.remote-repositories
      - ms-vsliveshare.vsliveshare
      - ms-vsliveshare.vsliveshare-audio
      - ms-vsliveshare.vsliveshare-pack
      - nicoespeon.abracadabra
      - orta.vscode-jest
      - pflannery.vscode-versionlens
      - phoenixframework.phoenix
      - redhat.vscode-yaml
      - silvenon.mdx
      - streetsidesoftware.code-spell-checker
      - styled-components.vscode-styled-components
      - stylelint.vscode-stylelint
      - thedavej.night-owl-black
      - timonwong.shellcheck
      - tombonnike.vscode-status-bar-format-toggle
      - wix.vscode-import-cost
      - wix.glean
      - wmaurer.change-case
    visual_studio_code_settings:
      {
        "[html]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[json]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[jsonc]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescriptreact]":
          { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[yaml]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "editor.cursorBlinking": "expand",
        "editor.cursorSmoothCaretAnimation": true,
        "editor.fontFamily": "Cutive Mono, Source Code Pro, Menlo, Monaco, Courier New, monospace",
        "editor.fontSize": 14,
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true,
        "editor.formatOnType": true,
        "editor.minimap.enabled": false,
        "editor.renderWhitespace": "all",
        "editor.tabSize": 2,
        "eslint.alwaysShowStatus": true,
        "eslint.format.enable": true,
        "eslint.lintTask.enable": true,
        "eslint.run": "onSave",
        "explorer.openEditors.visible": 0,
        "js/ts.implicitProjectConfig.checkJs": true,
        "javascript.suggest.completeFunctionCalls": true,
        "telemetry.telemetryLevel": "off",
        "typescript.updateImportsOnFileMove.enabled": "always",
        "window.titleBarStyle": "native",
        "workbench.colorTheme": "Night Owl Black",
        "workbench.settings.editor": "json",
        "workbench.sideBar.location": "right",
        "python.pythonPath": "/usr/bin/python3",
        "python.linting.enabled": true,
        "python.linting.mypyEnabled": true,
        "python.linting.flake8Enabled": true,
        "python.languageServer": "Pylance",
        "python.formatting.provider": "black",
        "workbench.editorAssociations": { "*.ipynb": "jupyter-notebook" },
        "terminal.integrated.tabs.enabled": true,
        "notebook.cellToolbarLocation":
          { "default": "right", "jupyter-notebook": "left" },
        "yaml.schemas":
          {
            "file:///Users/jamesdigioia/.vscode/extensions/atlassian.atlascode-2.10.12/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml",
          },
        "atlascode.jira.jqlList": [],
        "atlascode.bitbucket.enabled": false,
        "cSpell.userWords": ["financials", "oembed"],
        "redhat.telemetry.enabled": false,
        "editor.bracketPairColorization.enabled": true,
      }
