---
- name: copy dotfiles
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    backup: yes
  with_items:
    - aliases
    - apps
    - bash_profile
    - bashrc
    - exports
    - functions
    - gitconfig
    - gitignore_global
    - itermocil/domain.yml
    - itermocil/wp-gistpen.yml
    - path
