---
- name: install atom
  homebrew_cask:
    name: atom
    state: present

- name: copy atom config
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.atom/{{ item }}"
  with_items:
    - config.cson
    - init.coffee
    - keymap.cson
    - snippets.cson
    - styles.less

- name: install atom packages
  include_role:
      name: hnakamur.atom-packages
