---
- name: install atom
  homebrew_cask:
    name: atom
    state: present

- name: copy atom config
  copy:
    src: files/config.cson
    dest: "{{ ansible_env.HOME }}/config.cson"

- name: install atom packages
  include_role:
      name: hnakamur.atom-packages
