---
- name: install atom
  homebrew_cask:
    name: atom
    state: present

- name: copy atom config
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.atom/config.cson"
  with_items:
    - config.cson

- name: install atom packages
  include_role:
      name: hnakamur.atom-packages
