---
- name: copy dotfiles
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    backup: true
  with_items:
    - aliases
    - apps
    - bash_profile
    - bashrc
    - exports
    - functions
    - gitconfig
    - gitignore_global
    - path

- name: configure osx
  include_tasks: config-osx.yml
  when: ansible_distribution == 'MacOSX'

- name: configure ubuntu
  include_tasks: config-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
