---
- name: update and upgrade homebrew cask
  homebrew:
    upgrade_all: true

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_casks }}"

# - role: geerlingguy.mas # TODO(James) this fails in tests
#   tags: ["mas", "all"]
#   when: ansible_distribution == 'MacOSX'
