---
- name: Install node
  community.general.homebrew:
    name: node@{{ node_system_version | regex_replace('.x', '') }}
    state: present

- name: Install yarn
  community.general.homebrew:
    name: yarn
    state: present
