---
- name: Install fnm
  community.general.homebrew:
    name: fnm
    state: present

- name: Add fnm to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: true
    mode: "0644"
    marker: "### {mark} ANSIBLE MANAGED VOLTA CONFIG ###"
    block: |
      # Hook fnm into shell
      eval "$(fnm env \
        --use-on-cd \
        --version-file-strategy=recursive \
        --corepack-enabled \
        --resolve-engines \
        --shell bash)"
