---
- name: install node
  homebrew:
    name: node
    state: present

- name: install yarn
  homebrew:
    name: yarn
    state: present

- name: install nvm
  become: yes
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_install_path }}"
    depth: 1
    version: "v0.35.1"

- name: give nvm ownership to user
  become: yes
  file:
    dest: "{{ nvm_install_path }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: admin
    mode: u=rwX,g=rwX,o=rX
    recurse: yes

- name: make sure alias directory exists
  file:
    path: "{{ nvm_install_path }}/alias"
    state: directory

- name: make system default
  copy:
    src: default
    dest: "{{ nvm_install_path }}/alias/default"
    backup: yes

- name: add nvm to dotfiles
  blockinfile:
    path: "{{ ansible_env.HOME }}/.managed"
    create: yes
    marker: "### {mark} ANSIBLE MANAGED NVM CONFIG ###"
    block: |
      export NVM_DIR="{{ nvm_install_path }}"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
