windows:
    - name: "wp-gistpen"
      root: "~/Code"
      layout: double-main-horizontal
      panes:
        - commands:
            - pj jamesdigioia.com
            - cd server
            - vup
        - commands:
            - pj jamesdigioia.com
            - cd site
            - tail -f web/app/debug.log
        - commands:
            - pj jamesdigioia.com
            - cd site
        - commands:
            - pj wp-gistpen
            - npm i
            - npm run dev:app
        - commands:
            - pj wp-gistpen
            - bash bin/install-wp-tests.sh wordpress_test root password
