---
- name: install docker on ubuntu
  include_role:
    name: geerlingguy.docker
    apply:
      become: true
  when: ansible_distribution == 'Ubuntu'

- name: install docker on osx
  homebrew_cask:
    name: docker
    state: present
  when: ansible_distribution == 'MacOSX'
